### ISSUE TITLE
[Bug]: Azure reports are empty

### ISSUE THREAD

**Issue by BachateroJ** [toniblyx/prowler#2093]
### Steps to Reproduce

Tried using the prowler on an azure subscription, used the command:

prowler azure --az-cli-auth --subscription-ids [ID]

versions:
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"

prowler -v
Prowler 3.1.1

### Expected behavior

got this result in the cli:
```
╭────────────┬───────────┬────────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status     │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼────────────┼────────────┼────────┼──────────┼───────┤
│ azure      │ storage   │ FAIL (219) │          0 │     67 │       85 │    67 │
╰────────────┴───────────┴────────────┴────────────┴────────┴──────────┴───────╯
* You only see here those services that contains resources.
```
i can clearly see that there are findings for my account, however, the csv file im getting is empty 

### Actual Result with Screenshots or Logs

empty csv file

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

Ubuntu

### Prowler version

3.1.1

### Pip version

pip 20.0.2

**Comment by n4ch04** [comment]
Hi @BachateroJ you are using an outdated version of Prowler, latest coming from pip package is `3.2.4`
Can you update it with `pip install prowler --upgrade` and try again ?

Thanks for using Prowler !!

**Comment by toniblyx** [comment]
@BachateroJ you are using an old version of Prowler `3.1.1`, could you please upgrade it to the latest `3.3.0` and try again? that issue has been fixed already. Thanks!

```
pip install prowler --upgrade
```

**Comment by BachateroJ** [comment]
thanks for your response, im encountering an issue trying to upgrade:

prowler -v
Prowler 3.1.1

pip install prowler --upgrade
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: Could not find a version that satisfies the requirement prowler (from versions: none)
ERROR: No matching distribution found for prowler

**Comment by toniblyx** [comment]
Seems to be a dependency problem with something already installed. Can you try with this?

```
git clone https://github.com/prowler-cloud/prowler
cd prowler
poetry shell
poetry install
python prowler.py -v
```

Other installation options here: https://docs.prowler.cloud/en/latest/#installation

**Comment by Rdago** [comment]
In my case also empty report - tried pip install and @toniblyx method - both not working. 

```
prowler -v 
Prowler 3.3.0

python3.9 prowler.py -v
Prowler 3.3.0


```

**Comment by BachateroJ** [comment]
git clone didnt work for me
i solved the dependency problem, but still getting this:

prowler -v
Prowler 3.1.1

pip install prowler --upgrade
ERROR: Could not find a version that satisfies the requirement prowler (from versions: none)
ERROR: No matching distribution found for prowler

**Comment by Rdago** [comment]
it worked exporting in JSON format and then converting form JSON -> CSV with a third party tool.

**Comment by BachateroJ** [comment]
managed to update the prowler version, bug still persists:
```
╭────────────┬───────────┬────────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status     │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼────────────┼────────────┼────────┼──────────┼───────┤
│ azure      │ storage   │ FAIL (219) │          0 │     67 │       85 │    67 │
╰────────────┴───────────┴────────────┴────────────┴────────┴──────────┴───────╯
```
* You only see here those services that contains resources.

Detailed results are in:
 - CSV: /home/assaf/output/prowler-output-6a7f609-a64-20230320144302.csv
 - JSON: /home/assaf/output/prowler-output-c19fc94d0ca634-20230320144302.json

prowler -v
Prowler 3.3.0

**Comment by n4ch04** [comment]
Hi @BachateroJ we are going to review this and let you know asap 
Thanks for using Prowler !!!

**Comment by Tixavi** [comment]
Based on my tests, I can confirm that the scan seems to be working fine. When running the scan with the command `prowler azure --sp-env-auth --verbose`  we can see all the checks and a quick explanation for them.

However there is an issue in the reporting part: As shown by the screenshot of @BachateroJ, prowler outputs 2 files but they are empty (inside the CSV there is just the name of the columns and inside of the json file there is only an empty list: []). 
It would be nice to have a quick fix. 👍

**Comment by MrCloudSec** [comment]
Hi @Tixavi, can you execute the command with `--log-level ERROR` in case there are some errors in your execution regarding the creation of those files? Thanks.

**Comment by n4ch04** [comment]
Hi @Tixavi as @sergargar says, could you please launch the tool again with the flag `--log-level ERROR` and share the results ? 
@BachateroJ Can you launch the tool with the same flag to check what is happening?

Thanks

**Comment by Tixavi** [comment]
Hello @sergargar, I'm having the following error message multiple times.
```
2023-03-28 07:23:43,142 [File: outputs.py:174]  [Module: outputs]        ERROR: TypeError[137]: cannot unpack non-iterable NoneType object
2023-03-28 07:23:43,149 [File: models.py:97]    [Module: models]         ERROR: ValidationError[57]: 1 validation error for Azure_Check_Output_CSV
tenant_domain
  none is not an allowed value (type=type_error.none.not_allowed)
```
I have run `pip install prowler --upgrade` and `prowler -v` tells me I have Prowler 3.3.0.
I think it's probably because the `check_findings` is None/empty but it shouldn't since, with the verbose flag, I see the findings with the resource IDs like: 
```
Check ID: storage_secure_transfer_required_is_enabled - storage [medium]
        PASS storage: Storage account xxxxxxxxxxx from subscription yyyyyyyyyyyyy has secure transfer required enabled
```

**Comment by n4ch04** [comment]
Hi @BachateroJ @Tixavi2 @Rdago the issue has been solved here #2144, please check it out and feel free to reopen or open a new issue if the problems persist.

Thanks for using Prowler !!
