### ISSUE TITLE
Could not run with argurment "-s lambda" or "-s awslambda"

### ISSUE THREAD

**Issue by banv-dev** [toniblyx/prowler#5921]
### Steps to Reproduce

export LOG_LEVEL=INFO && python prowler.py aws -s lambda

### Expected behavior

Prowler should scan for awslambda service

### Actual Result with Screenshots or Logs

2024-11-27 13:57:25,877 [File: __main__.py:280]         [Module: __main__]       ERROR: There are no checks to execute. Please, check your input arguments

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Local PC

### OS used

MacOS Sonoma 14.6.1

### Prowler version

Prowler 5.0.0 (You are running the latest version, yay!)

### Pip version

pip 24.3.1

**Comment by jfagoagas** [comment]
Hello @banv-dev, we will review this and get back to you once we have an update.

Thanks for using Prowler!

**Comment by jfagoagas** [comment]
@banv-dev could you please test the above PR, branch is `PRWLR-5488-could-not-run-with-argurment-s-lambda-or-s-awslambda-5921`? We've fixed the issue!

**Comment by garym-krrv** [comment]
> PRWLR-5488-could-not-run-with-argurment-s-lambda-or-s-awslambda-5921

I just tested with the branch and it no longer errors @jfagoagas

**Comment by banv-dev** [comment]
I've just ran it again, it work. Thank you.

**Comment by AlisonVilela** [comment]
And I still have problems with this, I'm on version 5.6.0

It doesn't give an error, but I get the message `There are no findings in Account`, which is not true, because if I just run `prowler aws` the output contains the awslambda findings, but if I run `prowler aws -s awslambda` it says there are no findings.

**Comment by AlisonVilela** [comment]
![Image](https://github.com/user-attachments/assets/6031cf27-5fd7-4c75-aba9-cb8acf1225fd)
